# action.yml
name: 'Deploy to Cloudways'
description: 'Deploy your WordPress theme to your Cloudways server.'
inputs:
  cloudways_username:
    description: 'Username we are using to SSH into your Cloudways server. You need to have an SSH key setup for that user'
    required: true
  cloudways_server:
    description: 'IP of your Cloudways server.'
    required: true
  cloudways_deploy_path:
    description: 'Path where you wish to deploy your changes.'
    required: true
  cloudways_ssh_private_key:
    description: 'SSH key for your cloudways_username. You should add this through Github Secrets: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets'
    required: true
  cloudways_port:
    description: 'SSH port for SSH-ing into the target server.'
    required: false
    default: "22"
  build_script: 
    description: 'Here you can (optionally) define your build process (a.k.a. things that will run after your repository is clone but before deployment)'
    required: false
    default: ""
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'