# action.yml
name: 'Deploy to Cloudways'
description: 'Deploy your WordPress theme to your Cloudways server.'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: ''
  cloudways-username:
    description: 'Username we are using to SSH into your Cloudways server. You need to have an SSH key setup for that user'
    required: true
  cloudways-server:
    description: 'IP of your Cloudways server.'
    required: true
  cloudways-deploy-path:
    description: 'Path where you wish to deploy your changes.'
    required: true
  cloudways-ssh-key:
    description: 'SSH key for your cloudways-username. You should add this through Github Secrets: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'