on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          cloudways_username: 'test_username'
          cloudways_server: '123.123.123.33'
          cloudways_deploy_path: 'aaa'
          cloudways_ssh_private_key: ${{ secrets.TEST_CW_SSH_PRIVATE_KEY }}

