on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          cloudways-username: 'Test usernam,e'
          cloudways-server: 'tst Server'
          cloudways-deploy-path: 'aaa'
          # cloudways-ssh-key: 'aaa'

